{
  "openapi": "3.0.3",
  "info": {
    "title": "Restful API",
    "description": "Documentation",
    "version": "1.0.0"
  },
  "paths": {
    "/pokemons": {
      "get": {
        "tags": ["pokemons"],
        "summary": "Get all pokemon",
        "description": "",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "Page",
              "exclusiveMinimum": 0,
              "type": "integer"
            },
            "name": "page",
            "in": "query"
          },
          {
            "required": true,
            "schema": {
              "title": "Per Page",
              "exclusiveMinimum": 0,
              "type": "integer"
            },
            "name": "per_page",
            "in": "query"
          },
          {
            "required": false,
            "schema": {
              "title": "order_by",
              "enum": ["asc", "desc"],
              "type": "string"
            },
            "name": "order_by",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Request Success.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 200,
                  "status": true,
                  "message": "Request Success.",
                  "detail_message": null,
                  "results": {
                    "data": [],
                    "last_page": 4,
                    "page": 3,
                    "total": 15
                  }
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 422,
                  "status": false,
                  "message": "Unprocessable Entity.",
                  "detail_message": {
                    "_body": "Invalid input type."
                  },
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/battle": {
      "get": {
        "tags": ["pokemons"],
        "summary": "Simulate battle 5 pokemon",
        "description": "",
        "responses": {
          "200": {
            "description": "Request Success.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 200,
                  "status": true,
                  "message": "Request Success.",
                  "detail_message": null,
                  "results": {
                  }
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 422,
                  "status": false,
                  "message": "Unprocessable Entity.",
                  "detail_message": {
                    "_body": "Invalid input type."
                  },
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/battle-history": {
      "get": {
        "tags": ["pokemons"],
        "summary": "Get history battle pokemon",
        "description": "",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "Page",
              "exclusiveMinimum": 0,
              "type": "integer"
            },
            "name": "page",
            "in": "query"
          },
          {
            "required": true,
            "schema": {
              "title": "Per Page",
              "exclusiveMinimum": 0,
              "type": "integer"
            },
            "name": "per_page",
            "in": "query"
          },
          {
            "required": true,
            "schema": {
              "title": "start_datetime",
              "type": "string",
              "example": "2022-11-05 00:00:00"
            },
            "name": "start_datetime",
            "in": "query"
          },
          {
            "required": true,
            "schema": {
              "title": "end_datetime",
              "type": "string",
              "example": "2022-11-05 00:00:00"
            },
            "name": "end_datetime",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Request Success.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 200,
                  "status": true,
                  "message": "Request Success.",
                  "detail_message": null,
                  "results": {
                    "data": [],
                    "last_page": 4,
                    "page": 3,
                    "total": 15
                  }
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 422,
                  "status": false,
                  "message": "Unprocessable Entity.",
                  "detail_message": {
                    "_body": "Invalid input type."
                  },
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/pokemon-cheating/{battle_id}": {
      "post": {
        "tags": ["pokemons"],
        "summary": "Drop rank pokemon cheating in battle",
        "description": "",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "battle_id",
              "type": "string"
            },
            "name": "battle_id",
            "in": "path"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schema/PokemonCheating"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Request Success.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 200,
                  "status": true,
                  "message": "Request Success.",
                  "detail_message": null,
                  "results": {
                  }
                }
              }
            }
          },
          "404": {
            "description": "Resource Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 404,
                  "status": false,
                  "message": "Resource Not Found.",
                  "detail_message": {
                    "_app": "Battle not found."
                  },
                  "results": null
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 422,
                  "status": false,
                  "message": "Unprocessable Entity.",
                  "detail_message": {
                    "_body": "Invalid input type."
                  },
                  "data": null
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schema": {
      "ExampleResponse": {
        "title": "ExampleResponse",
        "type": "object",
        "required": ["status_code", "status", "message"],
        "properties": {
          "status_code": {
            "title": "status_code",
            "type": "integer"
          },
          "status": {
            "title": "status",
            "type": "boolean"
          },
          "message": {
            "title": "message",
            "type": "string"
          },
          "detail_message": {
            "title": "detail_message",
            "type": "string"
          },
          "results": {
            "title": "results",
            "type": "object"
          }
        }
      },
      "PokemonCheating": {
        "title": "PokemonCheating",
        "required": ["name"],
        "type": "object",
        "properties": {
          "name": {
            "title": "Name",
            "maxLength": 100,
            "minLength": 3,
            "type": "string"
          }
        }
      },

    }
  }
}
